name: HTML/CSS Validate & JS Unit Test

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/npm.lock') }}

      - name: Install packages
        run: npm install

      - name: JSCheck
        run: npm test
